### PR TITLE
fix!: Fix warnings about const variables must be in uppercase

### PR DESCRIPTION
**Pull request by pbackz**
Actual Behaviour : 

```bash
warning: associated constant `Control` should have an upper case name
   --> src/event/window_event.rs:250:15
    |
250 |         const Control     = 0b0010;
    |               ^^^^^^^ help: convert the identifier to upper case: `CONTROL`

warning: associated constant `Alt` should have an upper case name
   --> src/event/window_event.rs:252:15
    |
252 |         const Alt         = 0b0100;
    |               ^^^ help: convert the identifier to upper case: `ALT`

warning: associated constant `Super` should have an upper case name
   --> src/event/window_event.rs:254:15
    |
254 |         const Super       = 0b1000;
    |               ^^^^^ help: convert the identifier to upper case: `SUPER`

warning: associated constant `Shift` should have an upper case name
   --> src/event/window_event.rs:248:15
    |
248 |         const Shift       = 0b0001;
    |               ^^^^^ help: convert the identifier to upper case: `SHIFT``
```
Expected behaviour : none warnings

### CODE REVIEW

**Comment by pbackz** [comment]
Please, note that failed CI step is related to wasm target and involves all last PRs but not related with these current changes

```bash
error: the wasm32-unknown-unknown target is not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.3/src/lib.rs:219:9
    |
219 | /         compile_error!("the wasm32-unknown-unknown target is not supported by \
220 | |                         default, you may need to enable the \"js\" feature. \
221 | |                         For more information see: \
222 | |                         https://docs.rs/getrandom/#webassembly-support");```

**Comment by pbackz** [comment]
I fix the CI point in my commit 4e4f420d1e7566143bcfaeea940a0e3218151739. All works fine now :)

**Review by donkeyteethUX — CHANGES_REQUESTED** [review]
Thanks @pbackz. I'm inclined to keep the names of the keys as-is (removing warnings via `#![allow(non_upper_case_globals)]`). This is because 

1. `Key` is `pub`, meaning that this would technically be a breaking change. 
2. The names appear to have been mirrored from `glutin::event::VirtualKeyCode`, and the consistency is kind of nice imo.

Would you be interested in submitting an amended PR which keeps the wasm fix and fixes warnings by allowing lower case names?

**Comment by donkeyteethUX** [comment]
Closing since these items were addressed in https://github.com/sebcrozet/kiss3d/pull/288

**Pull request closed without merging**
