### PR TITLE
Bump nalgebra to a safe version

### PR DESCRIPTION
**Pull request by dmweis**
Hey,

This bumps version of nalgebra to new version which should be safe from https://github.com/dimforge/nalgebra/issues/883

I noticed issue mentioning that you don't have time to actively maintain this crate anymore so I figured I might save you some by just creating this PR myself even when it's a simple one.

I also saw that https://github.com/sebcrozet/kiss3d/pull/280 exists but it seems that it missed updating the `dev-dependencies`

## Testing

Since this crate doesn't have many tests I tested it by running the examples to make sure they work. I did this on a linux machine  but I think it's pretty safe to assume that it doesn't break anything on other platforms.

### CODE REVIEW

**Comment by dmweis** [comment]
I see that there is a failing test but it looks like it's failing on master as well

**Comment by karthikcl2590** [comment]
@dmweis are you planning to merge this?

**Comment by dmweis** [comment]
> @dmweis are you planning to merge this?

I will once it gets a review. But seems that this repo may be unmainted for now https://github.com/sebcrozet/kiss3d/issues/277

**Comment by karthikcl2590** [comment]
Thanks for your response! It looks like @donkeyteethUX just stepped up to help maintain! 
Also wonder if we could jump to a newer version while we're at it.

**Review by donkeyteethUX — CHANGES_REQUESTED** [review]
Thanks @dmweis. Can you update to `ncollide = 0.32` and `nalgebra = 0.29` while we're at it?

**Comment by dmweis** [comment]
> Thanks @dmweis. Can you update to `ncollide = 0.32` and `nalgebra = 0.29` while we're at it?

Done! I left the patch versions unbound as as this is how it was originally. Let me know if you think we should lock to a specific version.

Builds and tests on ubuntu with x11 correctly. Examples run too. Sadly I don't have other platforms to test on.

**Comment by dmweis** [comment]
Also thanks for joining this project as a maintainer @donkeyteethUX!

**Comment by karthikcl2590** [comment]
Seconded! Thanks to both of you :)

**Review by donkeyteethUX — APPROVED** [review]
Looks good to me. No issues with tests/examples on my linux machine.

**Comment by karthikcl2590** [comment]
@donkeyteethUX @dmweis it looks like the latest changes aren't pulled in via crates.io, i.e if my Cargo.toml looks like 
```
[dependencies]
kiss3d = "0.31"
```
Are you planning to publish a new version?

**Comment by dmweis** [comment]
If you need the fixed version right now you can tell cargo to pull it directly from github.

As long as you don't plan on publishing the package to crates.io that should be fine

**Comment by karthikcl2590** [comment]
Yep, I'm currently pointing Cargo to github (no plans on publishing to crates.io). Just wondering if a new kiss3d version is going to be published anytime soon.

**Comment by donkeyteethUX** [comment]
I bumped the package version to `0.32`. @sebcrozet can you run `cargo publish`?

**Pull request merged**
