### PR TITLE
Switch to web-sys instead of stdweb.

### PR DESCRIPTION
**Pull request by sebcrozet**
It appears that stdweb is mostly [dead](https://github.com/koute/stdweb/issues/403) so I would like to switch to web-sys/wasm-bindgen instead. This is a breaking change because:

- This completely removes the stdweb dependency in favor of web-sys. 
- This uses [glow](https://crates.io/crates/glow) instead of our generated webgl/opengl bindings.

### CODE REVIEW

**Comment by alvinhochun** [comment]
I've given it a few tries and had commented on it on discord, so I'm repeating them here for completeness.

On web it works mostly fine but I found some issues:

1. Right-click context menu isn't prevented from showing.
2. After Esc is pressed (thus ending the Kiss3d render loop), I continuously get uncaught error "closure invoked recursively or destroyed already" in the console.
3. Maybe one more (but might not be a regression): if the window is small enough that the canvas has a size of 0, it panics with "The aspect ratio must not be zero".

Running on native Windows results in an assertion failure panic in `Effect::drop` when closing the Kiss3d window.

**Comment by alvinhochun** [comment]
@sebcrozet You mentioned on discord that "glow does not have functions like is_shader, is_program etc.", can you open an issue on the `glow` repo to ask for them to be added?

**Comment by sebcrozet** [comment]
Thank you for your feedbacks @alvinhochun.

> You mentioned on discord that "glow does not have functions like is_shader, is_program etc.", can you open an issue on the glow repo to ask for them to be added?

I opened a [glow issue](https://github.com/grovesNL/glow/issues/116) about the missing `is_` functions.

> Running on native Windows results in an assertion failure panic in Effect::drop when closing the Kiss3d window.

If I remember correctly this was fixed in earlier versions of Kiss3d by validating that the shaders/programs being dropped are valid using the `is_shader/is_program` functions. So it is likely the problem appears again because of the lack of validation function in glow.

> Right-click context menu isn't prevented from showing.

Looks like something that should be configured in the `<canvas` style.

> After Esc is pressed (thus ending the Kiss3d render loop), I continuously get uncaught error "closure invoked recursively or destroyed already" in the console.

Weird, will have to investigate this.

> Maybe one more (but might not be a regression): if the window is small enough that the canvas has a size of 0, it panics with "The aspect ratio must not be zero".

This may be an assertion that did not exist before.

**Comment by alvinhochun** [comment]
> 
> > Right-click context menu isn't prevented from showing.
> 
> Looks like something that should be configured in the `<canvas` style.

Oh, for some reason I thought the past stdweb version called `e.preventDefault()` but looks like both versions actually behave the same way. Not a regression I suppose.

> 
> > Maybe one more (but might not be a regression): if the window is small enough that the canvas has a size of 0, it panics with "The aspect ratio must not be zero".
> 
> This may be an assertion that did not exist before.

Actually not a regression. The stdweb version also panics. Looks like it is caused by the camera code calling `Perspective3::set_aspect()` for the `FramebufferSize` event even when `w` is `0.0`, so not related to this change. Should be fixed separately though.

**Comment by alvinhochun** [comment]
> 
> > You mentioned on discord that "glow does not have functions like is_shader, is_program etc.", can you open an issue on the glow repo to ask for them to be added?
> 
> I opened a [glow issue](https://github.com/grovesNL/glow/issues/116) about the missing `is_` functions.
> 
> > Running on native Windows results in an assertion failure panic in Effect::drop when closing the Kiss3d window.
> 
> If I remember correctly this was fixed in earlier versions of Kiss3d by validating that the shaders/programs being dropped are valid using the `is_shader/is_program` functions. So it is likely the problem appears again because of the lack of validation function in glow.

#242 should fix these issues.

**Comment by alvinhochun** [comment]
> After Esc is pressed (thus ending the Kiss3d render loop), I continuously get uncaught error "closure invoked recursively or destroyed already" in the console.

@sebcrozet I suppose the only remaining blocker is this? I'm looking into it.

**Comment by sebcrozet** [comment]
Fixed the CI. Let's merge this!

**Pull request merged**
