### PR TITLE
canvas: Force correct drop order when render_loop ends

### PR DESCRIPTION
**Pull request by HenrySwanson**
First time contributing to this repo, lemme know if this PR is stylistically okay.

------------------------

After switching my application to use the `State`-based setup (see
examples/persistent_point_cloud.rs for an example), I would get errors
when closing the window:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1282`,
 right: `0`', C:\Users\Henry\.cargo\registry\src\github.com-1ecc6299db9ec823\kiss3d-0.31.0\src\resource\effect.rs:93:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1282`,
 right: `0`', C:\Users\Henry\.cargo\registry\src\github.com-1ecc6299db9ec823\kiss3d-0.31.0\src\resource\effect.rs:93:12
stack backtrace:
   0:     0x7ff64cfe157e - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff64cfe157e - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff64cfe157e - std::sys_common::backtrace::_print_fmt
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff64cfe157e - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff64cff626c - core::fmt::write
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\fmt\mod.rs:1092
   5:     0x7ff64cfdf068 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\io\mod.rs:1572
   6:     0x7ff64cfe402d - std::sys_common::backtrace::_print
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff64cfe402d - std::sys_common::backtrace::print
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff64cfe402d - std::panicking::default_hook::{{closure}}
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:208
   9:     0x7ff64cfe3af9 - std::panicking::default_hook
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:225
  10:     0x7ff64cfe46d3 - std::panicking::rust_panic_with_hook
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:591
  11:     0x7ff64cfe4281 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:497
  12:     0x7ff64cfe1e9f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff64cfe41d9 - std::panicking::begin_panic_handler
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:493
  14:     0x7ff64cffdbe0 - core::panicking::panic_fmt
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\panicking.rs:92
  15:     0x7ff64cff407a - core::fmt::Arguments::new_v1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\fmt\mod.rs:314
  16:     0x7ff64cff407a - core::panicking::assert_failed::inner
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\panicking.rs:135
  17:     0x7ff64ceb84dd - core::panicking::assert_failed<u32,u32>
                               at C:\Users\Henry\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\panicking.rs:143
  18:     0x7ff64cdf8782 - kiss3d::resource::effect::{{impl}}::drop
                               at C:\Users\Henry\.cargo\registry\src\github.com-1ecc6299db9ec823\kiss3d-0.31.0\src\resource\effect.rs:93
  19:     0x7ff64cd9ce4e - core::ptr::drop_in_place<kiss3d::resource::effect::Effect>
                               at C:\Users\Henry\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ptr\mod.rs:187
  20:     0x7ff64cd9d743 - core::ptr::drop_in_place<kiss3d::renderer::line_renderer::LineRenderer>
```

After enabling the logging in the `glow` crate, I found that the program
for the `LineRenderer` object in my state was suddenly becoming invalid
before I could call `IsProgram` and `DeleteProgram` on it. (Those are
from the `Drop` impl for `Effect`.)

The issued turned out to be that we were dropping the window before the
state, and since the window holds the OpenGL context, when we tried to
drop the state, we got errors.

This diff introduces a new struct that enforces the proper drop order,
and hides it behind a trait.

### CODE REVIEW

**Comment by HenrySwanson** [comment]
I think the ci error for wasm is unrelated to these changes, and is fixed by [this commit](https://github.com/sebcrozet/kiss3d/pull/285/commits/a4c3c56fa4763f0b0fa73050894a82cc8e7259f1) in #285.

**Comment by donkeyteethUX** [comment]
This looks reasonable. To clarify, how can the issue be reproduced exactly? Do you know if it's the same as
https://github.com/sebcrozet/kiss3d/issues/216 or https://github.com/sebcrozet/kiss3d/issues/131?

**Comment by HenrySwanson** [comment]
It can be reproduced with the `persistent_point_cloud` example, but I think it can be reproduced with any non-trivial State implementation. (Specifically, any time the `State` contains things that access the OpenGL context on Drop (e.g. `Effect`s)).

I think something different is going on in #131 and #216 . I copied the example from the former, and I still get the error. Adding in some logging, it crashes when the second `window.render()` is called. So maybe we're unable to create a second context? I'll look into it.

I copied the example from #131, and it still fails. When I wait

**Comment by HenrySwanson** [comment]
Okay, I think I have some idea of what's going on with those other two issues! I used the example in #134, where one window is created and closed, and then a second window is opened, but crashes on rendering.

The first loop, there's several program objects created. On my computer, the first window creates objects with IDs:
- 3: `LineRenderer`
- 6: `PlanarLineRenderer`
- 9: `PointRenderer`
- 12: `TextRenderer`
- 15: `ObjectMaterial`
- 18: `NormalsMaterial`
- 21: `UvsMaterial`

On the second attempt, we only create 3-12, but still try to call `gl.UseProgram(15)`, and this, of course, blows up, because we never created an object with that ID in this new context.

The reason this happens is that the materials manager maintains a cache of Program objects, and it has no way of knowing that the context underneath was invalidated.

I don't really know a good way of handling this. I think somehow the lifetime of the GL context has to be intertwined with this cache, but that seems quite difficult. :\

---

As an aside, here's the process I used to debug this. Partially to help others, but also because I know I'll forget later.

Fork a copy of `kiss3d` and a copy of `glow`. To wire the first to the second, add the following to kiss3d's `Cargo.toml`:
```
[dependencies]
glow = {version = <whatever your fork says>, features = ["debug_trace_calls"]}

[patch.crates-io]
glow = { path = "path/to/glow" }
```

Also, in GLOW's `Cargo.toml', add
```
[features]
debug_trace_calls = []
```

Then you'll see all the opengl calls printed in your output.

**Comment by donkeyteethUX** [comment]
Thanks for digging into this. I'll merge your changes and perhaps open a new issue for the other problem.

**Pull request merged**
